import React from 'react';

const Terms: React.FC = () => {
  return (
    <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 p-6 sm:p-8 md:p-10">
      <div className="max-w-4xl mx-auto prose dark:prose-invert prose-h1:text-3xl prose-h1:font-extrabold prose-h2:font-bold prose-h2:border-l-4 prose-h2:border-primary-500 prose-h2:pl-4 prose-a:text-primary-600 dark:prose-a:text-primary-400 hover:prose-a:underline">
        <h1>Terms of Service & Disclaimer</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400"><strong>Effective Date:</strong> August 26, 2025</p>

        <div className="bg-yellow-50 dark:bg-yellow-900/20 border-l-4 border-yellow-500 p-4 rounded-r-lg my-6">
            <p className="font-semibold text-yellow-800 dark:text-yellow-200">
            <strong>Disclaimer:</strong> This document is for informational purposes only and does not constitute legal advice. You should consult with a legal professional to ensure compliance with all applicable laws.
            </p>
        </div>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using EnhanceAiPrompt.com (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this Service.</p>

        <h2>2. Description of Services</h2>
        <p>EnhanceAiPrompt.com provides a suite of AI-powered tools designed to improve content creation and workflow efficiency. These tools include:</p>
        <ul>
            <li><strong>Prompt Enhancer:</strong> Refines user-submitted prompts to improve their clarity, detail, and effectiveness for AI models.</li>
            <li><strong>Content Humanizer:</strong> Rewrites text to sound more natural, engaging, and less robotic.</li>
            <li><strong>Image Generator:</strong> Creates visual images based on textual descriptions.</li>
            <li><strong>Text-to-Speech:</strong> Converts written text into spoken audio with a choice of voices.</li>
            <li><strong>Record Your Thoughts:</strong> Transcribes spoken audio into written text in real-time.</li>
            <li><strong>Blog:</strong> Features articles and news related to AI, technology, and prompt engineering.</li>
        </ul>

        <h2>3. AI-Generated Content Disclaimer</h2>
        <p><strong>All content, including text, images, and audio, generated by our tools is provided on an "AS-IS" basis without any warranties of any kind, express or implied.</strong></p>
        <p>The Service is powered by generative artificial intelligence (AI). AI-generated content can contain errors, inaccuracies, omissions, and may not be up-to-date. EnhanceAiPrompt.com is NOT responsible or liable for any content generated through the Service.</p>
        <p><strong>User's Responsibility:</strong> You are solely responsible for reviewing and verifying all generated content for accuracy, legality, and appropriateness. You must not rely on generated content as a substitute for professional advice (e.g., legal, financial, medical). You must ensure that your use of the generated content complies with all applicable laws and does not infringe on any third-party rights.</p>
        
        <h2>4. User Responsibilities and Conduct</h2>
        <ul>
            <li><strong>Account Security:</strong> You are responsible for maintaining the confidentiality of your account information and are fully responsible for all activities that occur under your account.</li>
            <li><strong>Prohibited Use:</strong> You agree not to use the Service to generate any content that is illegal, defamatory, harmful, abusive, infringing, or otherwise objectionable.</li>
        </ul>
        
        <h2>5. Intellectual Property</h2>
        <p>You, the user, retain all intellectual property rights to the content you generate and download using the Service, provided your input and use of the output comply with these Terms. We claim no ownership over the content you create.</p>
        
        <h2>6. Limitation of Liability</h2>
        <p>In no event shall EnhanceAiPrompt.com or its owner be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in any way connected with the use of our Service.</p>
        
        <h2>7. Governing Law</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of the state of Uttar Pradesh, India, without regard to its conflict of law provisions.</p>
        
        <h2>8. Changes to Terms</h2>
        <p>We reserve the right to modify these terms at any time. We will do so by posting and drawing attention to the updated terms on the Site. Your decision to continue to visit and make use of the Site after such changes have been made constitutes your formal acceptance of the new Terms of Service.</p>

        <h2>9. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us at: <a href="mailto:mailtoanujgoel@gmail.com">mailtoanujgoel@gmail.com</a></p>
      </div>
    </div>
  );
};

export default Terms;
